services:
  # Base de datos PostgreSQL para FieldPal
  fieldpal-pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: fieldpal-pg-db-container
    environment:
      POSTGRES_DB: ${BD_NAME}
      POSTGRES_USER: ${BD_USER}
      POSTGRES_PASSWORD: ${BD_PWD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5432
    volumes:
      - fieldpal-pg-data:/var/lib/postgresql
      #- ./src/main/resources/db/initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql
    networks:
      - fieldpal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${BD_NAME} -U ${BD_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Interfaz gráfica pgAdmin4
  pgadmin4:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "adminBD@postgres.org"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 82:80
    depends_on:
      - fieldpal-pg-db
    networks:
      - fieldpal-network

networks:
  fieldpal-network:
    driver: bridge

volumes:
  fieldpal-pg-data:
    name: fieldpal-pg-data-local